apiVersion: v1
kind: Namespace
metadata:
  name: k3s-ia-lab
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfire
  name: xmpp-lb
  namespace: k3s-ia-lab
spec:
  ports:
    - name: xmpp
      port: 5222
      protocol: TCP
      targetPort: 5222
  selector:
    app: openfire
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfire
  name: openfire-service
  namespace: k3s-ia-lab
spec:
  ports:
    - name: admin-console
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: inverse
      port: 7070
      protocol: TCP
      targetPort: 7070
  selector:
    app: openfire
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: openfire
  name: openfire
  namespace: k3s-ia-lab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: openfire
  template:
    metadata:
      labels:
        app: openfire
    spec:
      containers:
        - image: registry.gitlab.com/soapboxrace/openfire:5.0.2
          env:
            - name: OPENFIRE_FQDN
              value: xmpp.k3s-ia-lab.lan
          imagePullPolicy: Always
          name: openfire
          ports:
            - containerPort: 9090
              protocol: TCP
            - containerPort: 5222
              protocol: TCP
            - containerPort: 7070
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: k3s-ia-lab
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      restartPolicy: Always
      runtimeClassName: nvidia
      containers:
        - name: ollama-container
          image: ollama/ollama:0.13.2
          ports:
            - containerPort: 11434
              name: http
              protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: "1Gi"
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
          volumeMounts:
            - name: ollama-storage
              mountPath: /root/.ollama
      volumes:
        - name: ollama-storage
          hostPath:
            path: /mnt/data/ollama
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: k3s-ia-lab
  labels:
    app: ollama
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
  selector:
    app: ollama
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: k3s-ia-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13.7-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "password"
            - name: RABBITMQ_FRAME_MAX
              value: "4096"
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-lb
  namespace: k3s-ia-lab
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: k3s-ia-lab
spec:
  selector:
    app: rabbitmq
  ports:
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n
  namespace: k3s-ia-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:1.121.3
          env:
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: DB_TYPE
              value: "postgresdb"
            - name: DB_POSTGRESDB_HOST
              value: "postgres-lb.k3s-ia-lab.svc.cluster.local"
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: "n8n"
            - name: DB_POSTGRESDB_USER
              value: "postgres"
            - name: DB_POSTGRESDB_PASSWORD
              value: "mysecurepassword"
          ports:
            - containerPort: 5678
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          hostPath:
            path: /mnt/data/n8n
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: k3s-ia-lab
spec:
  selector:
    app: n8n
  ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: k3s-ia-lab
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:0.8.1-pg18-trixie
          env:
            - name: POSTGRES_PASSWORD
              value: "mysecurepassword"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-data
          hostPath:
            path: /mnt/data/postgres
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: k3s-ia-lab
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k3s-ia-lab
  namespace: k3s-ia-lab
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: n8n.k3s-ia-lab.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n-service
                port:
                  number: 5678
    - host: xmpp-adm.k3s-ia-lab.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openfire-service
                port:
                  number: 9090
    - host: rabbitmq.k3s-ia-lab.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq-service
                port:
                  number: 15672
    - host: open-webui.k3s-ia-lab.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-webui-service
                port:
                  number: 8080
    - host: auth.k3s-ia-lab.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
    - host: grafana.k3s-ia-lab.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: xmppweb-redirect
  namespace: k3s-ia-lab
spec:
  redirectRegex:
    regex: ^(https?://)xmpp\.k3s-ia-lab\.lan/?$
    replacement: ${1}xmpp.k3s-ia-lab.lan/xmppweb/
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xmpp
  namespace: k3s-ia-lab
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: k3s-ia-lab-xmppweb-redirect@kubernetescrd
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  rules:
    - host: xmpp.k3s-ia-lab.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openfire-service
                port:
                  number: 7070

