apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: erpnext
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: erpnext
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: frappe/erpnext:v16.7.3
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MARIADB_ROOT_PASSWORD
              value: "admin"
          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites
            - name: logs
              mountPath: /home/frappe/frappe-bench/logs
      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: sites-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: logs-pvc
