
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: erpnext
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: db
spec:
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
  namespace: erpnext
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: erpnext
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
            - "--skip-character-set-client-handshake"
            - "--skip-innodb-read-only-compressed"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MARIADB_ROOT_PASSWORD
              value: "admin"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - "-h"
                - localhost
                - "--password=admin"
            periodSeconds: 30
            failureThreshold: 20
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - "-h"
                - localhost
                - "--password=admin"
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc
