---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  namespace: erpnext
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: redis-cache
spec:
  selector:
    app: redis-cache
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  namespace: erpnext
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: redis-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
