apiVersion: v1
kind: Service
metadata:
  name: redis-queue
  namespace: erpnext
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: redis-queue
spec:
  selector:
    app: redis-queue
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-queue-data-pvc
  namespace: erpnext
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-queue
  namespace: erpnext
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: redis-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-queue
  template:
    metadata:
      labels:
        app: redis-queue
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-queue-data
              mountPath: /data
      volumes:
        - name: redis-queue-data
          persistentVolumeClaim:
            claimName: redis-queue-data-pvc
