apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: erpnext
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: frappe/erpnext:v16.7.3
          args:
            - "bench"
            - "schedule"
          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites
            - name: logs
              mountPath: /home/frappe/frappe-bench/logs
      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: sites-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: logs-pvc
