apiVersion: v1
kind: Namespace
metadata:
  name: open-webui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui-container
          image: ghcr.io/open-webui/open-webui:v0.7.2
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: OLLAMA_BASE_URL
              value: "http://ollama-service.ollama.svc.cluster.local:11434"
            - name: WEBUI_URL
              value: "http://open-webui.uaiso.lan/"
            - name: OPENID_PROVIDER_URL
              value: "http://auth.uaiso.lan/realms/uaiso/.well-known/openid-configuration"
            - name: OAUTH_CLIENT_ID
              value: "open-webui-client"
            - name: OAUTH_CLIENT_SECRET
              value: "AEm8dhQuIKaRBwqhaj9q3tscD36PEOI3"
            - name: ENABLE_OAUTH_SIGNUP
              value: "true"
            - name: OAUTH_PROVIDER_NAME
              value: "Keycloak"
            - name: OAUTH_SCOPES
              value: "openid email profile"
            - name: OPENID_REDIRECT_URI
              value: "http://open-webui.uaiso.lan/oauth/oidc/callback"
            - name: DEFAULT_USER_ROLE
              value: "admin"
            - name: WEBUI_AUTH_SIGNOUT_REDIRECT_URL
              value: "http://open-webui.uaiso.lan"
            - name: ENABLE_PASSWORD_AUTH
              value: "false"
            - name: ENABLE_LOGIN_FORM
              value: "false"
            - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
              value: "true"
            - name: DATABASE_TYPE
              value: "postgres"
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "mysecurepassword"
            - name: DATABASE_HOST
              value: "postgresql.postgresql.svc.cluster.local"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "openwebui"
              # if using pgvector, uncomment the following lines
#            - name: PGVECTOR_DB_URL
#              value: "postgresql://postgres:mysecurepassword@postgresql.postgresql.svc.cluster.local:5432/openwebuipgvector"
#            - name: VECTOR_DB
#              value: pgvector
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: open-webui
  labels:
    app: open-webui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: open-webui
---
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui
  namespace: open-webui
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: open-webui.uaiso.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-webui-service
                port:
                  number: 8080
