apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/uaiso-serious/infra'
      targetRevision: main
      path: apps/argocd/helm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
status: {}